"""Common import lookup tables."""

common_libraries = ("typing",)

common_statements: dict[str, str] = {
    "ABC": "from abc import ABC",
    "AsyncIterator": "from collections.abc import AsyncIterator",
    "AsyncMock": "from unittest.mock import AsyncMock",
    "BaseModel": "from pydantic import BaseModel",
    "BeautifulSoup": "from bs4 import BeautifulSoup",
    "Callable": "from collections.abc import Callable",
    "Depends": "from fastapi import Depends",
    "Enum": "from enum import Enum",
    "Field": "from pydantic import Field",
    "Image": "from PIL import Image",
    "Iterator": "from collections.abc import Iterator",
    "MagicMock": "from unittest.mock import MagicMock",
    "NamedTemporaryFile": "from tempfile import NamedTemporaryFile",
    "Path": "from pathlib import Path",
    "StringIO": "from io import StringIO",
    "TYPE_CHECKING": "from typing import TYPE_CHECKING",
    "TemporaryDirectory": "from tempfile import TemporaryDirectory",
    "UUID": "from uuid import UUID",
    "ValidationError": "from pydantic import ValidationError",
    "YAMLError": "from yaml import YAMLError",
    "abstractmethod": "from abc import abstractmethod",
    "assert_never": "from typing import assert_never",
    "asynccontextmanager": "from contextlib import asynccontextmanager",
    "config": "from decouple import config",
    "cv": "import cv2 as cv",
    "datetime": "from datetime import datetime",
    "logger": "from loguru import logger",
    "patch": "from unittest.mock import patch",
    "sa": "import sqlalchemy as sa",
    "sp": "import subprocess as sp",
    "suppress": "from contextlib import suppress",
    "timedelta": "from datetime import timedelta",
    "timezone": "from datetime import timezone",
    "tz": "from dateutil import tz",
}
