"""Common import lookup tables."""

# Libraries scanned for exports when a name is not found via common_statements
# or as a top-level module. Order matters: earlier entries win on name collisions.
common_libraries = (
    "typing",
    "collections.abc",
    "collections",
    "functools",
    "dataclasses",
    "contextlib",
    "pathlib",
    "re",
    "enum",
)

common_statements: dict[str, str] = {
    "ABC": "from abc import ABC",
    "AsyncIterator": "from collections.abc import AsyncIterator",
    "AsyncMock": "from unittest.mock import AsyncMock",
    "BaseModel": "from pydantic import BaseModel",
    "BeautifulSoup": "from bs4 import BeautifulSoup",
    "Callable": "from collections.abc import Callable",
    "Depends": "from fastapi import Depends",
    "Enum": "from enum import Enum",
    "Field": "from pydantic import Field",
    "Image": "from PIL import Image",
    "Iterator": "from collections.abc import Iterator",
    "MagicMock": "from unittest.mock import MagicMock",
    "NamedTemporaryFile": "from tempfile import NamedTemporaryFile",
    "Path": "from pathlib import Path",
    "TYPE_CHECKING": "from typing import TYPE_CHECKING",
    "UUID": "from uuid import UUID",
    "ValidationError": "from pydantic import ValidationError",
    "YAMLError": "from yaml import YAMLError",
    "abstractmethod": "from abc import abstractmethod",
    "assert_never": "from typing import assert_never",
    "asynccontextmanager": "from contextlib import asynccontextmanager",
    "cv": "import cv2 as cv",
    "datetime": "from datetime import datetime",
    "defaultdict": "from collections import defaultdict",
    "deque": "from collections import deque",
    "namedtuple": "from collections import namedtuple",
    "np": "import numpy as np",
    "patch": "from unittest.mock import patch",
    "pd": "import pandas as pd",
    "plt": "import matplotlib.pyplot as plt",
    "sa": "import sqlalchemy as sa",
    "sp": "import subprocess as sp",
    "timedelta": "from datetime import timedelta",
}
