"""Common import lookup tables."""

# Libraries scanned for exports when a name is not found via common_statements
# or as a top-level module. Order matters: earlier entries win on name collisions.
common_libraries = (
    "typing",
    "collections.abc",
    "collections",
    "functools",
    "dataclasses",
    "contextlib",
    "pathlib",
    "re",
    "enum",
)

common_statements: dict[str, str] = {
    "ABC": "from abc import ABC",
    "AsyncIterator": "from collections.abc import AsyncIterator",
    "AsyncMock": "from unittest.mock import AsyncMock",
    "BaseModel": "from pydantic import BaseModel",
    "BeautifulSoup": "from bs4 import BeautifulSoup",
    "Callable": "from collections.abc import Callable",
    "ChainMap": "from collections import ChainMap",
    "Counter": "from collections import Counter",
    "Depends": "from fastapi import Depends",
    "Enum": "from enum import Enum",
    "Field": "from pydantic import Field",
    "Image": "from PIL import Image",
    "Iterator": "from collections.abc import Iterator",
    "MagicMock": "from unittest.mock import MagicMock",
    "Match": "from re import Match",
    "NamedTemporaryFile": "from tempfile import NamedTemporaryFile",
    "OrderedDict": "from collections import OrderedDict",
    "Path": "from pathlib import Path",
    "Pattern": "from re import Pattern",
    "StringIO": "from io import StringIO",
    "TYPE_CHECKING": "from typing import TYPE_CHECKING",
    "TemporaryDirectory": "from tempfile import TemporaryDirectory",
    "UUID": "from uuid import UUID",
    "ValidationError": "from pydantic import ValidationError",
    "YAMLError": "from yaml import YAMLError",
    "abstractmethod": "from abc import abstractmethod",
    "assert_never": "from typing import assert_never",
    "asynccontextmanager": "from contextlib import asynccontextmanager",
    "chain": "from itertools import chain",
    "combinations": "from itertools import combinations",
    "config": "from decouple import config",
    "count": "from itertools import count",
    "cycle": "from itertools import cycle",
    "cv": "import cv2 as cv",
    "datetime": "from datetime import datetime",
    "defaultdict": "from collections import defaultdict",
    "deque": "from collections import deque",
    "groupby": "from itertools import groupby",
    "islice": "from itertools import islice",
    "logger": "from loguru import logger",
    "mpl": "import matplotlib as mpl",
    "namedtuple": "from collections import namedtuple",
    "np": "import numpy as np",
    "nx": "import networkx as nx",
    "pairwise": "from itertools import pairwise",
    "patch": "from unittest.mock import patch",
    "permutations": "from itertools import permutations",
    "pd": "import pandas as pd",
    "plt": "import matplotlib.pyplot as plt",
    "product": "from itertools import product",
    "repeat": "from itertools import repeat",
    "sa": "import sqlalchemy as sa",
    "starmap": "from itertools import starmap",
    "takewhile": "from itertools import takewhile",
    "tee": "from itertools import tee",
    "zip_longest": "from itertools import zip_longest",
    "sns": "import seaborn as sns",
    "sp": "import subprocess as sp",
    "suppress": "from contextlib import suppress",
    "tf": "import tensorflow as tf",
    "timedelta": "from datetime import timedelta",
    "timezone": "from datetime import timezone",
    "tz": "from dateutil import tz",
}
