[project]
version = "2.0.0"
authors = [
    {name = "Lyz", email = "lyz@riseup.net"},
    {name = "Oscar", email = "ocaballeror@tutanota.com"},
]
license = {text = "GPL-3.0-only"}
requires-python = ">=3.14"
dependencies = [
    "click>=8.4.1",
    "maison>=2.0.2",
    "pyprojroot>=0.3.0",
    "ruff>=0.15.14",
    "xdg-base-dirs>=6.0.2",
]
name = "autoimport"
description = "Autoimport missing python libraries."
readme = "README.md"
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Topic :: Utilities",
    "Natural Language :: English",
]

[project.urls]
Issues = "https://github.com/ocaballeror/autoimport/issues"
homepage = "https://github.com/ocaballeror/autoimport"
documentation = "https://lyz-code.github.io/autoimport"

[project.scripts]
autoimport = "autoimport.entrypoints.cli:cli"

[dependency-groups]
doc = [
    "mkdocs>=1.6.1",
    "mkdocs-git-revision-date-localized-plugin>=1.5.2",
    "mkdocs-htmlproofer-plugin>=1.5.0",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocs-autolinks-plugin>=0.7.1",
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.4",
    "markdown-include>=0.8.1",
    "mkdocs-section-index>=0.3.12",
]
dev = [
    "pre-commit>=4.6.0",
    "mypy>=2.1.0",
    "types-toml>=0.10.8.20260518",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
]

[build-system]
requires = ["uv_build>=0.11.16,<0.12"]
build-backend = "uv_build"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-vv -rs --tb=short"
norecursedirs = [
    ".tox",
    ".git",
    "*/migrations/*",
    "*/static/*",
    "docs",
    "venv",
    "*/Autoimport/*",
    "*/deepdiff/*"
]

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'if TYPE_CHECKING:',
    'raise NotImplementedError',
    'if __name__ == "__main__":',
]

[tool.mypy]
python_version = 3.14
show_error_codes = true
ignore_missing_imports = false
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
warn_unused_configs = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disable_error_code = "import-untyped"

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_decorators = false
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.ruff]
line-length = 100
target-version = "py314"

[tool.ruff.lint]
select = ["F", "E", "I001", "TID", "UP"]
fixable = ["ALL"]

[tool.ruff.format]
line-ending = "auto"
