# --------- uv -------------

[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
dynamic = ["version"]
authors = [
    {name = "Lyz", email = "lyz@riseup.net"},
]
license = {text = "GPL-3.0-only"}
requires-python = ">=3.13"
dependencies = [
    "autoflake",
    "click",
    "maison",
    "pyflakes",
    "pyprojroot",
    "xdg",
]
name = "autoimport"
description = "Autoimport missing python libraries."
readme = "README.md"
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Utilities",
    "Natural Language :: English",
]

[project.urls]
Issues = "https://github.com/lyz-code/autoimport/issues"
homepage = "https://github.com/lyz-code/autoimport"
documentation = "https://lyz-code.github.io/autoimport"

[project.scripts]
autoimport = "autoimport.entrypoints.cli:cli"

[dependency-groups]
doc = [
    "mkdocs>=1.6.0",
    "mkdocs-git-revision-date-localized-plugin>=1.1.0",
    "mkdocs-htmlproofer-plugin>=0.8.0",
    "mkdocs-minify-plugin>=0.5.0",
    "mkdocs-autolinks-plugin>=0.6.0",
    "mkdocs-material>=8.4.2",
    "mkdocstrings[python]>=0.18",
    "markdown-include>=0.7.0",
    "mkdocs-section-index>=0.3.4",
]
dev = [
    "pre-commit>=2.20.0",
    "mypy>=0.971",
    "types-toml>=0.10.3",
    "pytest>=7.1.3",
    "pytest-cov>=3.0.0",
    "ruff>=0.14.0"
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

# --------- Autoimport -------------

[tool.autoimport.common_statements]
"factories" = "from tests import factories"


# --------- Pytest -------------

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-vv -rs --tb=short"
norecursedirs = [
    ".tox",
    ".git",
    "*/migrations/*",
    "*/static/*",
    "docs",
    "venv",
    "*/Autoimport/*",
    "*/deepdiff/*"
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "secondary: mark tests that use functionality tested in the same file (deselect with '-m \"not secondary\"')"
]

# --------- Coverage -------------

[tool.coverage.report]
exclude_lines = [
    # Have to re-enable the standard pragma
    'pragma: no cover',

    # Type checking can not be tested
    'if TYPE_CHECKING:',

    # Ignore the Abstract classes definition
    'raise NotImplementedError',

    # Ignore entrypoints
    'if __name__ == "__main__":',
]

# --------- Mypy -------------

[tool.mypy]
python_version = 3.13
show_error_codes = true
ignore_missing_imports = false
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
warn_unused_configs = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disable_error_code = "import-untyped"

[[tool.mypy.overrides]]
module = "tests.*"
# Required to not have  error: Untyped decorator makes function on fixtures and
# parametrize decorators
disallow_untyped_decorators = false
disallow_untyped_defs = false
disallow_incomplete_defs = false

# --------- Ruff -------------

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["F", "E", "I001", "TID", "UP"]
fixable = ["ALL"]

[tool.ruff.format]
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
